image: azul/zulu-openjdk-alpine:19

git-leaks:
  stage: .pre
  image:
    name: "zricethezav/gitleaks:latest"
    entrypoint: [ "" ]
  script:
    - gitleaks detect --verbose --redact --no-git --source="$CI_PROJECT_DIR"
  tags:
    - docker

# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

sast:
  stage: test
  variables:
    SAST_JAVA_VERSION: 18
    SAST_EXCLUDED_ANALYZERS: "eslint"

include:
  - template: Security/SAST.gitlab-ci.yml

unit-test:
  stage: test
  script:
    - apk --no-cache add curl
    - curl --version
    - suffix=$([[ $(uname -m) == "aarch64" ]] && echo "arm64" || echo "x86-64")
    - curl -L -o agent https://app.testcontainers.cloud/download/testcontainers-cloud-agent_linux_$suffix
    - chmod +x agent
    - ./agent &
    - ./agent wait
    - chmod +x gradlew
    - ./gradlew jacocoTestReport
    - cat build/reports/jacoco/test/html/index.html
  tags:
    - docker
