# This workflow builds the Docker image for the gitlab-issue-importer and then deploys the application.
name: 05 - Build and deploy the application to AWS

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

on:
  workflow_run:
    workflows: [ 01 - Run application tests ]
    types: [ completed ]
    branches: [ main ]

jobs:
  changes:
    name: Detect relevant source changes
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      main: ${{ steps.filter.outputs.main }}
      gradle: ${{ steps.filter.outputs.gradle }}
      dockerfile: ${{ steps.filter.outputs.dockerfile }}
      workflow-deploy: ${{ steps.filter.outputs.workflow-deploy }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Run changes detection
        uses: dorny/paths-filter@v2.11.1
        id: filter
        with:
          filters: |
            app:
              - 'app/src/main/**'
            cdk:
              - 'cdk/**/*Service*'
            gradle-app:
              - 'app/build.gradle.kts'
            gradle-cdk:
              - 'cdk/build.gradle.kts'
            dockerfile:
              - 'Dockerfile'
            workflow-deploy:
              - '.github/workflows/cdk-05-build-and-deploy.yml'

  build-and-publish:
    name: Build and publish the application
    runs-on: ubuntu-22.04
    outputs:
      DOCKER_IMAGE_TAG: ${{ steps.create-docker-image-tag.outputs.DOCKER_IMAGE_TAG }}
    needs: changes
    if: ${{ needs.changes.outputs.app == 'true' || ${{ needs.changes.outputs.cdk == 'true' || needs.changes.outputs.gradle-app == 'true' || needs.changes.outputs.gradle-cdk == 'true' || needs.changes.outputs.dockerfile == 'true' || needs.changes.outputs.workflow-deploy == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to AWS
        run:  aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

      - name: Create Docker image tag
        id: create-docker-image-tag
        run: echo "DOCKER_IMAGE_TAG=$(date +'%Y%m%d%H%M%S')-${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Publish Docker image to ECR registry
        env:
          DOCKER_IMAGE_TAG: ${{ steps.create-docker-image-tag.outputs.DOCKER_IMAGE_TAG }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/gitlab-issue-importer:${DOCKER_IMAGE_TAG}
            ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/gitlab-issue-importer:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  deploy:
    runs-on: ubuntu-22.04
    name: Deploy the application
    needs: build-and-publish
    timeout-minutes: 15
    if: github.ref == 'refs/heads/main'
    concurrency: gitlab-issue-importer-deployment
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          java-package: jdk
          cache: 'gradle'

      - name: NPM install
        working-directory: cdk
        run: |
          npm i -D aws-cdk@latest
          rm -fr node_modules package-lock.json cdk.out
          npm i

      - name: Deploy service stack to staging
        working-directory: cdk
        env:
          DOCKER_IMAGE_TAG: ${{ needs.build-and-publish.outputs.DOCKER_IMAGE_TAG }}
        run: npm run service:deploy -- -c dockerImageTag=${DOCKER_IMAGE_TAG} -c environmentName=staging
